#{{- $email := promptString "email" -}}
#sourceDir = "{{ .chezmoi.homedir }}/Backup/DottedFilesHL"
#sourceDir = "/home/marco/Backup/DottedFilesHL"
encryption = "gpg"

[gpg]
  recipient = "D4C501DA48EB797A081750939449C2F50996635F"

[data]
#  email = "{{ $email }}"
  name = "Marco Trevisan"
#  sshKey = "{{ $email }} SSH key"

#[sourceVCS]
  #autoCommit = true
  #autoPush = true
